# Generated by Django 3.2.18 on 2026-02-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateivelichro2', '0003_auto_20230603_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='co2_items_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('item_unit', models.CharField(max_length=25)),
                ('item_co2perunit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='co2_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(202601, 202601), (202602, 202602)])),
                ('item_name', models.CharField(choices=[('LPG', 'LPG'), ('Gasoline', 'Gasoline'), ('Elec_ap8', 'Electricity for ap. 8'), ('Elec_ap20', 'Electricity for ap. 20'), ('Gas_ap8', 'Gas for ap. 8'), ('Gas_ap20', 'Gas for ap. 20'), ('Work_flight', 'Work flights'), ('Leisure_flight', 'Leisure flights')], max_length=250)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='co_rolling_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('item_name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
