# Generated by Django 3.2.18 on 2026-04-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.CreateModel(
            name='deforest_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('path', models.CharField(max_length=250)),
            ],
        ),
    ]
